### ISSUE TITLE
broken recipe

### ISSUE THREAD

**Issue by abdelhakim96** [sintef-ocean/conan-casadi#1]
Hi, I get the following error trying to use your casadi/3.5.5. Can you please help me with the error?

*********************************************************
Recipe 'casadi/3.5.5@sintef/stable' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'casadi/3.5.5@sintef/stable' not resolved: casadi/3.5.5@sintef/stable: Cannot load recipe.

**Comment by joakimono** [comment]
The error you get is because the recipe is written for conan v1, and you use conan v2. Unfortunately, there are no immediate plans to migrate this recipe to support conan v2. You might have some luck by downgrading to conan v1 `pip install --upgrade conan=~1.0`. However, I suspect you will run into several other issues, since the recipe is 3 years old.

**Comment by abdelhakim96** [comment]
Alright, thanks for your answer!
